= csoftz-gap-insurance README

V1.0.0-May.07/2018

Here we can find an excercise a CRUD interface for insurance policy.

Here we find some folders.
The main folder is named 'app-code' which contains all the source code for the solution.
Therein you can find the folder: 'microservices'.

The 'microservices' folder holds a ASP.NET Core (Version 2.x) solution, it is
thought as it were to be a microservice.

The .NET solution holds two projects. One is a ASP.NET Core Web API which implements
the whole REST API. The data storages points to a PostgreSQL server.

The other project is ASP.NET Core MVC Web App to consume that API.

In order to run this application, you will need to have a PostgreSQL server (v10) used.
The 'docs' directory contains a 'database' folder with the required scripts to create 
and populate a initial database.

== Guide

To install postgreSQL support.
Add 'ngpgsql' nuget package.
Then add 'Dapper' ORM add 'dapper' nuget package.

Follow along this video if you need to use EF Core.
https://www.youtube.com/watch?v=md20lQut9EE Uses Entity Framework underneath.

== Database
This application uses 'postgreSQL', next is the version used:
PostgreSQL 10.1 on x86_64-apple-darwin, compiled by i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00), 64-bit

NOTE: The project was build on a MacBook Pro, using Mac OS X (High Sierra).

The folder *_'docs/database/postgresql'_* contains the required scripts to create 
the database objects.

The execution order is as follows:

- create_database.sql
- create_sequences.sql
- create_tables.sql
- create_view.sql
- insert_data.sql

== REST API URLs
Following you will find the URLs to get to each REST API method.

NOTE: The home for rest api is http://localhost:5000

=== Coverage Type
GET: /insurance/api/v1/coveragetype/all

=== Insurance Policy
GET:    /insurance/api/v1/insurancepolicy/all
POST:   /insurance/api/v1/insurancepolicy
PUT:    /insurance/api/v1/insurancepolicy/{id}
DELETE: /insurance/api/v1/insurancepolicy/{id}

=== Risk Type
GET: /insurance/api/v1/risktype/all

=== User
GET: /insurance/api/v1/user/all

=== User Insurance Policy
GET: /insurance/api/v1/userinsurancepolicy/all

== Web MVC App
Following are the URLs to use to register *_Insurance Policy_* and link to *_Users_*.

[NOTE] 
====
The home for web site is http://localhost:5001.
In the menu bar you will find two entries to Pages to register
*_Insurance Policy_* and *_User Insurance Policy_*.
====

=== Register Insurance Policy
The menu entry is called 
http://localhost:5001/InsurancePolicy

=== Link Insurance Policies to Users
http://localhost:5001/UserInsurancePolicy
